### PR TITLE
Add Server Administrator as an appointed officer

### PR DESCRIPTION
**Pull request by hjarrell**
Add the position of Server Administrator to the constitution. This position will be in charge of the Open Source Club's server.

### CODE REVIEW

**Comment by xeranimus** [comment]
Should we add any requirements for this position (e.g. prior experience)?

**Comment by hjarrell** [comment]
> Should we add any requirements for this position (e.g. prior experience)?

My personal view on this is that that can be left up to the President. The constitution makes no note of any requirements or lack of requirements that a President can have when getting applicants. It only says 

> The Server Administrator shall be appointed by the President.

So the president can literally makeup whatever requirements they want to have.

**Comment by mirdaki** [comment]
I would also add they should maintain a common record of any server settings they change (so it would be easy to create a new server or let future people figure out bugs) like [this one](https://github.com/ufosc/club-stack/blob/master/docs/server-setup.md).

**Comment by xeranimus** [comment]
> 
> 
> > Should we add any requirements for this position (e.g. prior experience)?
> 
> My personal view on this is that that can be left up to the President. The constitution makes no note of any requirements or lack of requirements that a President can have when getting applicants. It only says
> 
> > The Server Administrator shall be appointed by the President.
> 
> So the president can literally makeup whatever requirements they want to have.

That's a fair point. We don't have any explicit requirements for other positions.

**Comment by hjarrell** [comment]
Approved at GBM 2/20/2018

**Pull request merged**
